import type { InputHTMLAttributes, JSX, Ref } from "react";

/**
 * The tick box, in the tool's own ink.
 *
 * **The defect this exists to have fixed was the absence of styling** (design change 6, findings
 * B-56/B-73). A raw `<input type="checkbox">` paints its tick with the browser's `accent-color`,
 * which on every default install is a saturated blue — the most saturated colour anywhere in the
 * builder, belonging to no ramp, in a tool built on one warm ground and one ink (`SPEC.md` §3,
 * §6). Nothing in the markup said so: the class list was empty, so the fault was invisible to
 * anyone reading the source and only showed up in a rendered screen.
 *
 * `accent-ink` is generated by `@theme`'s `--color-ink`, so the box is the same ink as the type
 * beside it and cannot drift from it. Native rendering is kept deliberately — an
 * `appearance-none` box redrawn from a border and a background is a container, and paper builds
 * structure from space rather than from containers (§7.4). The browser's own tick, in our ink,
 * is the smallest change that puts the colour back on the ramp.
 *
 * **The box is stepped up to 1.25rem** from the browser's ~0.8125rem. At default size it reads as
 * a stray mark rather than as a control next to the body type beside it.
 *
 * **The tap floor belongs to the row, not to the box** (§7.6). `tap` is `min-height: 2.75rem`,
 * and a checkbox 1.25rem wide by 2.75rem tall is a stretched rectangle in every engine that
 * paints the native control. Both call sites press the whole `<label>` — which is what the
 * pointer actually hits — and it is the label that carries `tap`.
 */

/** The one recipe. Exported so `controls.test.ts` can assert on it rather than re-spell it. */
export const CHECKBOX_CLASS = "size-5 shrink-0 accent-ink";

export interface CheckboxProps extends Omit<InputHTMLAttributes<HTMLInputElement>, "type"> {
  readonly ref?: Ref<HTMLInputElement>;
}

export function Checkbox({ className, ...rest }: CheckboxProps): JSX.Element {
  return (
    <input type="checkbox" className={`${CHECKBOX_CLASS} ${className ?? ""}`.trim()} {...rest} />
  );
}
