import type { InputHTMLAttributes, JSX, Ref } from "react";

/**
 * The radio, in the tool's own ink (#375; the pattern is `Checkbox.tsx`, #193).
 *
 * **The defect is the absence of styling, again.** The style row's five closed sets — shape,
 * lettering, light or dark, how times read, the week starts on — were raw `<input type="radio">`,
 * and a raw radio paints its dot with the browser's `accent-color`: a saturated blue that
 * belongs to no ramp, on a paper built from one warm ground and one ink (`SPEC.md` §7.4). The
 * class list was empty, so nothing in the source said so; it showed in a rendered screen only.
 *
 * `accent-ink` is generated by `@theme`'s `--color-ink`, so the dot is the same ink as the word
 * beside it and cannot drift from it. Native rendering is kept deliberately, for the reason the
 * tick box keeps it: an `appearance-none` circle redrawn from a border and a fill is a container,
 * and paper builds structure from space rather than from containers.
 *
 * **The same size as the tick box**, 1.25rem, so a screen holding both — the advanced panel's
 * switch under the style row's radios — shows one family of marks rather than two.
 *
 * **The tap floor belongs to the label, not to the circle** (§7.6), exactly as for the tick box:
 * `tap` is a min-height, and a circle held to 2.75rem tall is an oval. Every call site presses
 * the whole `<label>`, and the label carries `tap`.
 *
 * **The hours step's day segments do not come here.** Their radios are `sr-only` — the segment
 * the owner presses is the label around one, wearing `theme.css`'s `picked` mark — so there is
 * no native rendering to put in ink. `controls.test.ts` lets a hidden radio stay raw for that
 * reason, and only a hidden one.
 */

/** The one recipe. Exported so `controls.test.ts` can assert on it rather than re-spell it. */
export const RADIO_CLASS = "size-5 shrink-0 accent-ink";

export interface RadioProps extends Omit<InputHTMLAttributes<HTMLInputElement>, "type"> {
  readonly ref?: Ref<HTMLInputElement>;
}

export function Radio({ className, ...rest }: RadioProps): JSX.Element {
  return <input type="radio" className={`${RADIO_CLASS} ${className ?? ""}`.trim()} {...rest} />;
}
